### PR TITLE
add widescreen_cheat for DC gundamdx

### PR DESCRIPTION
**Pull request by inada-s**
Investigation log: https://github.com/inada-s/gdxsv/issues/138

Since disc1 has a slightly different memory layout, only disc2 is supported this time.

### CODE REVIEW

**Comment by inada-s** [comment]
The current version may be affecting the game logic.
Need carefully verify before merging.
image

**Comment by vkedwardli** [comment]
I would like to create a new tab for gdxsv related settings (for better user experience, and also we don’t need to rely on Flycast’s widescreen game cheat option but without using the Cheat engine)

It will allow custom aspect ratio settings, and laid the foundation for the future translation selection menu

How does it sound to you?

**Comment by inada-s** [comment]
I think adding menus to the UI is a change that makes conflicts more likely and makes it more expensive to keep up with upstream.

I don't like hard forks, because I've seen many times where people have put in modifications they liked to themselves, couldn't keep up with the upstream, and were left with the old version.
Ideally, I'd like to put the server support for gdxsv into mainstream flycast, or offer it as a plugin.
(So I would have preferred to use modem emulation if I could have solved the performance problem.

**Comment by inada-s** [comment]
for now I'm prioritizing being able to play on the 16/9 screen without large graphic glitches.

**Pull request merged**
