### PR TITLE
Merge upstream 20210614

### PR DESCRIPTION
**Pull request by inada-s**
### upstream version: https://github.com/flyinghead/flycast/commit/b8c2a695b8e0a209f92ca56c8dfa659f3cceae99
- [x] windows build
- [x] macOS build
- [x] windows compatibility test (out sync test)
- [x] macOS compatibility test (out sync test)
- [x] check updated features
- [ ] ~~use github actions to release~~ I'll do this after the PR merged
- [x] remove appveyor.yml
- [x] change release tag (conflict with upstream tags)

## Points to pay attention to
https://github.com/inada-s/flycast/pull/34/commits/6c0b357e81c501a82a26d2ac9173ec429c705fd7
- ~~crypto/sha1 is going to be removed (cannot use it)~~ solved
- ~~config class changes. need to check old fields in emu.cfg.~~ ok
- ~~no_popup_opend: call of overloaded 'IsPopupOpen(int, ImGuiPopupFlags_)' is ambiguous~~ solved
- etc...

### CODE REVIEW

**Comment by vkedwardli** [comment]
- For the crypto folder which is going to be removed in https://github.com/flyinghead/flycast/pull/271, can we just readd it after the PR is merged?
- The `no_popup_opened()` is for checking if there is any opened popup, or else the Flycast UI would stuck when we are trying to display 2 popup at the same time. E.g. LAN cable reminder and New Update prompt (v0.7.7 has this bug)

**Comment by inada-s** [comment]
The CPU usage of the cmake build version seems to be quite low.
image

**Comment by inada-s** [comment]
`fast-math` option is removed from upstream.
https://github.com/flyinghead/flycast/commit/5227259048003db3895be88dc68593736a57a58f

**Comment by scribam** [comment]
About this

>For the crypto folder which is going to be removed in flyinghead#271, can we just readd it after the PR is merged?

Do you know you can generate hash using xxHash which is included in Flycast's deps? Or is it mandatory to use sha1?

**Comment by vkedwardli** [comment]
@scribam I picked SHA-1 due to popularity (or my lack of knowledge LOL) only, didn't know there is xxHash, thanks for the info

**Comment by inada-s** [comment]
I've already used sha1, but haven't really depended on sha1 yet, so I'll switch to xxhash.
Thank you for the information.

**Comment by inada-s** [comment]
On my mac: BigSur 11.3.1（20E241）
```
$ open -n Flycast.app
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2539, NSUnderlyingError=0x7ff874e148c0 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x7ff874e0af20 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed with error: 111}}}}}
```

**Comment by vkedwardli** [comment]
@inada-s can you open the original Flycast and our original v0.7.8 on Big Sur?

**Comment by inada-s** [comment]
> can you open the original Flycast and our original v0.7.8 on Big Sur?

yes I can open latest upstream flycast

**Comment by inada-s** [comment]
https://developer.apple.com/forums/thread/666611
chmod workaround work

**Pull request merged**
