### PR TITLE
Fix macOS out sync

### PR DESCRIPTION
**Pull request by vkedwardli**
I noticed that there is trigonometric calculation mismatch across macOS and Windows.

The below sample code

```cpp
//#include <stdio.h>
//#include <math.h>

volatile double num = 1.56497856262158219209;
volatile double numHalf = num / 2.0;

volatile double cosVal = cos(num);
volatile double cosValHalf = cos(numHalf);

printf("num = %.100g\n", num);
printf("numHalf = %.100g\n", numHalf);
printf("cosVal(num) = %.100g\n", cosVal);
printf("cosValHalf(numHalf) = %.100g\n", cosValHalf);
    
volatile float temp1 = 62981764.0000000000000000f;
volatile float temp2 = (2.14859168E8f  *  atanf(temp1));
printf("temp2: %.100g\n", temp2);
```
would print:

| value | macOS libm | MinGW-w64 libm | |
| --- | --- | --- | --- |
| num | 1.56497856262158219209368326119147241115570068359375 | 1.56497856262158219209368326119147241115570068359375 | ✅ |
| numHalf | 0.782489281310791096046841630595736205577850341796875 | 0.782489281310791096046841630595736205577850341796875 | ✅ |
| cosVal(num) | 0.005817731354993829**935573490530487106298096477985382080078125** | 0.005817731354993829**0682117525420835590921342372894287109375** | ❌ |
| cosValHalf(numHalf) | 0.709160676911443577097315937862731516361236572265625 | 0.709160676911443577097315937862731516361236572265625 | ✅ |
| temp2 | 337**499968** | 337**500000** | ❌ |

So it seems that the math library from macOS is quite inaccurate. 
(`math.h` functions is provided by `/usr/lib/libm.dylib@ -> libSystem.dylib`, `-lm` is not required on macOS, and you can't unlink `libSystem.dylib`?)

***   
\
Link with OpenLibm, trying to override the original libm on macOS:
| value | macOS OpenLibm | MinGW-w64 libm | |
| --- | --- | --- | --- |
| num | 1.56497856262158219209368326119147241115570068359375 | 1.56497856262158219209368326119147241115570068359375 | ✅ |
| numHalf | 0.782489281310791096046841630595736205577850341796875 | 0.782489281310791096046841630595736205577850341796875 | ✅ |
| cosVal(num) | 0.0058177313549938290682117525420835590921342372894287109375 | 0.0058177313549938290682117525420835590921342372894287109375 | ✅ |
| cosValHalf(numHalf) | 0.709160676911443**68811961840037838555872440338134765625** | 0.709160676911443**577097315937862731516361236572265625** | ❌ |
| temp2 | 337500000 | 337500000 | ✅ |

More accurate now, but still doesn't match.

***
\
So linking OpenLibm on Windows also:
| value | macOS OpenLibm | MinGW-w64 OpenLibm | |
| --- | --- | --- | --- |
| num | 1.56497856262158219209368326119147241115570068359375 | 1.56497856262158219209368326119147241115570068359375 | ✅ |
| numHalf | 0.782489281310791096046841630595736205577850341796875 | 0.782489281310791096046841630595736205577850341796875 | ✅ |
| cosVal(num) | 0.0058177313549938290682117525420835590921342372894287109375 | 0.0058177313549938290682117525420835590921342372894287109375 | ✅ |
| cosValHalf(numHalf) | 0.70916067691144368811961840037838555872440338134765625 | 0.70916067691144368811961840037838555872440338134765625 | ✅ |
| temp2 | 337500000 | 337500000 | ✅ |
***

### TODO: Need to verify if it is really the case that, `libm` can be overriden by "linking" only.

Out sync is not fixed yet

### CODE REVIEW

**Comment by inada-s** [comment]
It's a good approach. I hope this solve the out-sync.

**Comment by vkedwardli** [comment]
Found no problems in recompiler and interpreter, both macOS and Windows FPU results are identical (except some ordering difference during printf).

Turns out [`-ffast-math`](https://gcc.gnu.org/wiki/FloatingPointMath) is the culprit, enabling `GCC_FAST_MATH` in Xcode is the finishing blow.

Seems using  `-ffast-math` has nearly no performance gain with dynarec(?), and since the original Dreamcast hardware (SH-4) should be conforming to the IEEE754 standard, may be `-ffast-math` is required for better performance with the interpreter?

If we are aiming at console/dreamcast accuracy, with dynarec may be `-ffast-math` should be removed from both platforms? (But can player really notice it? 🤯)

**Comment by inada-s** [comment]
I think `-ffast-math` should be removed for gdxsv If the CPU usage does not change significantly.

**Comment by vkedwardli** [comment]
Thanks, removed and good to merge now

**Pull request merged**
